"""Build the small icon font the app ships with.

Material Symbols is a 4 MB variable font with every icon. The app uses
one style and about sixty icons, so this script:
  1. finds every icon name used in src/ (quoted words that are icon names),
  2. pins the variable axes to the style in tokens.css (FILL 0, wght 500, GRAD 0, opsz 20),
  3. keeps only the glyphs for those icons, addressed by code point,
  4. writes src/shared/styles/icons/material-symbols-subset.woff2 and
     src/shared/ui/iconCodepoints.ts (name to code point, and the IconName type).

Rerun after using a new icon (tsc reports an unknown icon name):
    pip install -r scripts/requirements.txt
    python scripts/subset_icons.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "node_modules" / "material-symbols" / "material-symbols-outlined.woff2"
SRC = ROOT / "src"
FONT_OUT = SRC / "shared" / "styles" / "icons" / "material-symbols-subset.woff2"
MAP_OUT = SRC / "shared" / "ui" / "iconCodepoints.ts"
AXES = {"FILL": 0, "wght": 500, "GRAD": 0, "opsz": 20}
QUOTED_WORD = re.compile(r"""["'`]([a-z][a-z0-9_]*)["'`]""")


def icon_code_points(font: TTFont) -> dict[str, int]:
    """Icon name to code point, read from the font's ligature and cmap tables."""
    cmap = font.getBestCmap()
    char_of = {glyph: chr(cp) for cp, glyph in cmap.items() if cp < 0x80}
    point_of = {glyph: cp for cp, glyph in cmap.items() if cp >= 0xE000}
    names: dict[str, int] = {}
    for lookup in font["GSUB"].table.LookupList.Lookup:
        for table in lookup.SubTable:
            table = getattr(table, "ExtSubTable", table)
            for first, ligatures in getattr(table, "ligatures", {}).items():
                for lig in ligatures:
                    glyphs = [first, *lig.Component]
                    if all(g in char_of for g in glyphs) and lig.LigGlyph in point_of:
                        names["".join(char_of[g] for g in glyphs)] = point_of[lig.LigGlyph]
    return names


def used_names(known: dict[str, int]) -> list[str]:
    found: set[str] = set()
    for path in SRC.rglob("*.ts*"):
        if path == MAP_OUT or "test" in path.parts:
            continue
        found.update(w for w in QUOTED_WORD.findall(path.read_text(encoding="utf-8")) if w in known)
    return sorted(found)


def write_map(names: list[str], points: dict[str, int]) -> None:
    lines = [
        "/** Generated by scripts/subset_icons.py. Do not edit by hand. */",
        "export const ICON_CODE_POINTS = {",
        *[f"  {name}: 0x{points[name]:x}," for name in names],
        "} as const;",
        "",
        "export type IconName = keyof typeof ICON_CODE_POINTS;",
        "",
    ]
    MAP_OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    font = TTFont(SOURCE)
    points = icon_code_points(font)
    names = used_names(points)
    if not names:
        print("No icon names found in src/", file=sys.stderr)
        return 1

    static = instancer.instantiateVariableFont(font, AXES)
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = []
    options.name_IDs = ["*"]
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=[points[n] for n in names])
    subsetter.subset(static)

    FONT_OUT.parent.mkdir(parents=True, exist_ok=True)
    static.flavor = "woff2"
    static.save(FONT_OUT)
    write_map(names, points)
    print(f"{len(names)} icons, {FONT_OUT.stat().st_size / 1024:.1f} KB -> {FONT_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
